;;; org-upwell-demo.el --- Generated data to develop against  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 yoshzucker

;; Author: yoshzucker
;; URL: https://github.com/yoshzucker/org-upwell

;; This file is not part of GNU Emacs.

;;; Commentary:

;; A small GTD project with files, generated.  Not mixed into the real
;; ones: `org-upwell-demo-mode' points `org-agenda-files' and the store
;; at a disposable directory, and switching off puts them back.
;;
;; Dates are computed, never written down -- the same reason
;; org-foresight-demo does it that way.  Regenerating is the way back
;; to a known state after a drop or a claim has been tried.
;;
;; The heading to drop onto is "File the photos".  Expanding it opens
;; the bench without opening the files, so the first act can be the
;; drop.

;;; Code:

(require 'org)
(require 'org-id)
(require 'org-upwell-core)
(require 'org-upwell-bench)

(defgroup org-upwell-demo nil
  "Generated data for developing org-upwell."
  :group 'org-upwell
  :prefix "org-upwell-demo-")

(defcustom org-upwell-demo-directory
  (locate-user-emacs-file "org-upwell-demo/")
  "Where the generated demo files are written.
Machine-local and disposable: everything in it is rewritten by
`org-upwell-demo-regenerate'."
  :type 'directory
  :group 'org-upwell-demo)

(defvar org-upwell-demo--saved nil
  "State captured when `org-upwell-demo-mode' was switched on.")

(defconst org-upwell-demo-id-quotes "org-upwell-demo-quotes")
(defconst org-upwell-demo-id-drop   "org-upwell-demo-drop")
(defconst org-upwell-demo-id-url    "org-upwell-demo-url")
(defconst org-upwell-demo-id-project "org-upwell-demo-project")

(defun org-upwell-demo--files-dir ()
  "Directory of dummy attachments for the demo."
  (expand-file-name "files" org-upwell-demo-directory))

(defun org-upwell-demo--write-bytes (path contents)
  "Write CONTENTS to PATH, creating parent directories."
  (make-directory (file-name-directory path) t)
  (with-temp-file path (insert contents)))

(defun org-upwell-demo--projects ()
  "Return the demo project file.

Three headings, three jobs for the package:

- Compare the three quotes -- already has files, so the bench has
  something to show: both sections, and a form column with six different
  answers in it
- File the photos -- empty on purpose; this is the drop target
- Read the vendor manual -- a URL and the download of it, so a claim is
  not always a path and two rows can be one document

Under one project, because a family is what `org-upwell-matrix\=' is of:
three siblings passing the same documents along is the shape that makes a
grid worth drawing, and three top-level headings would draw a grid one
column wide."
  (concat
   "#+title: Projects (org-upwell demo)\n"
   "# Generated by org-upwell-demo-regenerate.  Edits will be lost.\n\n"
   "* Move to the new vendor\n"
   ":PROPERTIES:\n"
   ":ID:        " org-upwell-demo-id-project "\n"
   ":UPWELL_DIR: " (org-upwell-demo--files-dir) "\n"
   ":END:\n"
   "The family.  `T\' on the bench draws the three tasks below as a grid:\n"
   "rows are the documents, columns are the tasks, a cell is a claim.\n"
   "UPWELL_DIR says where the work is done -- the bench marks that row\n"
   "`main\', and `M\' moves a download into it.\n\n"
   "** NEXT Compare the three quotes\n"
   ":PROPERTIES:\n"
   ":ID:       " org-upwell-demo-id-quotes "\n"
   ":CATEGORY: procurement\n"
   ":EFFORT:   0:30\n"
   ":END:\n"
   "Two quotes are confirmed (pin/drop).  brief.txt is provisional\n"
   "(the shape a clock-attribution has before you keep it).\n"
   "Directories are listed above files: where the work is kept is a thing\n"
   "to go to, and `^\' goes there.  `P\' keeps the place a row lives in.\n"
   "The recording is upwell.org next to this file; `o' on the bench visits it.\n\n"
   "*** NEXT Send the recommendation\n"
   ":PROPERTIES:\n"
   ":EFFORT:   0:15\n"
   ":END:\n\n"
   "** NEXT File the photos\n"
   ":PROPERTIES:\n"
   ":ID:       " org-upwell-demo-id-drop "\n"
   ":CATEGORY: admin\n"
   ":EFFORT:   0:15\n"
   ":END:\n"
   "Empty on purpose.  Drop a file or URL onto the bench.\n\n"
   "** NEXT Read the vendor manual\n"
   ":PROPERTIES:\n"
   ":ID:       " org-upwell-demo-id-url "\n"
   ":CATEGORY: procurement\n"
   ":EFFORT:   0:10\n"
   ":END:\n"
   "A URL, and the download of it.  Two records -- one is a link somebody\n"
   "else can open, the other is a file on this machine -- and the bench\n"
   "says the second is a copy of the first.\n"))

(defun org-upwell-demo-files ()
  "Return the demo Org files as a list of absolute paths."
  (list (expand-file-name "projects.org" org-upwell-demo-directory)))

(defun org-upwell-demo--seed-store ()
  "Write upwell.org against the generated files, claimed to demo ids.

Enough kinds of thing that every column on the bench has something to
say: a directory and a sub-directory, so the listing has both of its
sections; a spreadsheet, a deck and a PDF, so the form column is not one
word repeated; a SharePoint short link, which says which application
opens it and not what it is called; a site page, which is not a document
at all; and a download of the PDF, so the row that is the same document
as the one above it says so."
  (let* ((dir (org-upwell-demo--files-dir))
         (acme (expand-file-name "quote-acme.csv" dir))
         (beta (expand-file-name "quote-beta.txt" dir))
         (brief (expand-file-name "brief.txt" dir))
         (deck (expand-file-name "kickoff.pptx" dir))
         (shared (expand-file-name "shared" dir))
         (copy (expand-file-name "vendor manual.pdf" dir)))
    (org-upwell-demo--write-bytes
     acme "item,qty,price\nwidget,3,1200\n")
    (org-upwell-demo--write-bytes
     beta "Beta Co. quote\n- 3 widgets at 1100\n- delivery Friday\n")
    (org-upwell-demo--write-bytes
     brief "One-page brief for the vendor meeting.\n")
    (org-upwell-demo--write-bytes
     deck "Not really a deck; the extension is the point.\n")
    (org-upwell-demo--write-bytes
     copy "Not really a PDF; being a download of the URL above is the point.\n")
    (make-directory shared t)
    (let ((org-upwell-directory org-upwell-demo-directory)
          (store (expand-file-name org-upwell-file-name
                                   org-upwell-demo-directory)))
      (when (file-exists-p store) (delete-file store))
      (when-let ((buf (get-file-buffer store)))
        (with-current-buffer buf (set-buffer-modified-p nil))
        (kill-buffer buf))
      (org-upwell-claim
       (org-upwell-save (list :path acme :name "quote-acme.csv"
                              :provenance "demo"))
       org-upwell-demo-id-quotes 'confirmed)
      (org-upwell-claim
       (org-upwell-save (list :path beta :name "quote-beta.txt"
                              :provenance "demo"))
       org-upwell-demo-id-quotes 'confirmed)
      (org-upwell-claim
       (org-upwell-save (list :path brief :name "brief.txt"
                              :provenance "demo"))
       org-upwell-demo-id-quotes 'provisional)
      ;; the two sections: the tree the work is kept in, and one inside it
      (org-upwell-claim
       (org-upwell-save (list :path dir :provenance "demo"))
       org-upwell-demo-id-quotes 'confirmed)
      (org-upwell-claim
       (org-upwell-save (list :path shared :provenance "demo"))
       org-upwell-demo-id-quotes 'provisional)
      (org-upwell-claim
       (org-upwell-save (list :path deck :name "kickoff.pptx"
                              :provenance "demo"))
       org-upwell-demo-id-quotes 'confirmed)
      ;; A short link says which application opens it and nothing else -- and
      ;; it is on two tasks, which is the shape `org-upwell-matrix' is for.
      ;; A family passes its documents along, and one of the headings it
      ;; lands on should not have it; a single bench cannot show that,
      ;; because what is wrong is a relation between two of them.
      (let ((deck (org-upwell-save
                   (list :url "https://contoso.sharepoint.com/:p:/r/sites/proc/Doc.aspx?sourcedoc=%7B1%7D"
                         :name "Vendor day deck"
                         :provenance "demo"))))
        ;; Threaded: the claims written are the ones on the item handed in.
        (setq deck (org-upwell-claim deck org-upwell-demo-id-quotes 'confirmed))
        (org-upwell-claim deck org-upwell-demo-id-url 'provisional))
      ;; and a page is not a document
      (org-upwell-claim
       (org-upwell-save
        (list :url "https://contoso.sharepoint.com/sites/proc/SitePages/vendors.aspx"
              :name "Vendor list"
              :provenance "demo"))
       org-upwell-demo-id-quotes 'provisional)
      (org-upwell-claim
       (org-upwell-save
        (list :url "https://example.com/vendor/manual.pdf"
              :name "vendor manual"
              :provenance "demo"))
       org-upwell-demo-id-url 'confirmed)
      ;; downloaded and kept: two things, and the bench says they are one
      ;; document
      (org-upwell-claim
       (org-upwell-save (list :path copy :name "vendor manual.pdf"
                              :provenance "demo"))
       org-upwell-demo-id-url 'confirmed))))

;;;###autoload
(defun org-upwell-demo-regenerate ()
  "Write the demo files afresh.
Also the way back to a known state after dropping, pinning or claiming."
  (interactive)
  (make-directory org-upwell-demo-directory t)
  (make-directory (org-upwell-demo--files-dir) t)
  (let ((path (expand-file-name "projects.org" org-upwell-demo-directory)))
    (when-let ((buf (get-file-buffer path)))
      (with-current-buffer buf (set-buffer-modified-p nil))
      (kill-buffer buf))
    (with-temp-file path (insert (org-upwell-demo--projects))))
  (org-upwell-demo--seed-store)
  (when (called-interactively-p 'interactive)
    (message "Demo data regenerated in %s" org-upwell-demo-directory))
  (org-upwell-demo-files))

(defun org-upwell-demo--goto-drop ()
  "Visit the empty drop-target heading and open its bench."
  (let ((file (expand-file-name "projects.org" org-upwell-demo-directory)))
    (find-file file)
    (goto-char (point-min))
    (unless (re-search-forward (regexp-quote org-upwell-demo-id-drop) nil t)
      (user-error "org-upwell-demo: drop heading missing"))
    (org-back-to-heading t)
    (org-upwell--bench-draw (org-upwell-domain (point-marker)))))

;;;###autoload
(define-minor-mode org-upwell-demo-mode
  "Point the store and the agenda at generated demo data.

Switching on regenerates the data, redirects `org-agenda-files' and
`org-upwell-directory', and opens the empty heading with its bench so
a drop can be tried immediately.  Switching off puts the real files
back.  Real `upwell.org' is never touched."
  :global t
  :group 'org-upwell-demo
  :lighter " Upwell-demo"
  (if org-upwell-demo-mode
      (progn
        (setq org-upwell-demo--saved
              (list :agenda-files (bound-and-true-p org-agenda-files)
                    :directory org-upwell-directory
                    :expand-max org-upwell-bench-open-max
                    :open-location org-upwell-bench-open-location
                    :todo-keywords org-todo-keywords))
        (setq org-todo-keywords
              '((sequence "NEXT" "ONGO" "|" "DONE" "CANCEL")
                (sequence "WAIT" "|" "DELEG")))
        (org-upwell-demo-regenerate)
        (setq org-agenda-files (org-upwell-demo-files)
              org-upwell-directory org-upwell-demo-directory
              ;; Bench only: opening the dummy csv in Numbers is not
              ;; the thing being demonstrated, and it hides the drop.
              org-upwell-bench-open-max 0
              org-upwell-bench-open-location nil)
        (org-upwell-demo--goto-drop)
        (message "Upwell demo on.  Drop onto the bench.  o opens %s (same format as real use)."
                 (org-upwell-file)))
    ;; Switching off a demo that was never on has nothing to put back,
    ;; and putting nothing back would empty `org-agenda-files'.
    (when org-upwell-demo--saved
      (setq org-agenda-files (plist-get org-upwell-demo--saved :agenda-files)
            org-upwell-directory (plist-get org-upwell-demo--saved :directory)
            org-upwell-bench-open-max (plist-get org-upwell-demo--saved :expand-max)
            org-upwell-bench-open-location
            (plist-get org-upwell-demo--saved :open-location)
            org-todo-keywords (plist-get org-upwell-demo--saved :todo-keywords)
            org-upwell-demo--saved nil))
    (org-upwell--quit-bench-window)
    (message "Upwell demo off; agenda and upwell.org back to the real files")))

(provide 'org-upwell-demo)

;;; org-upwell-demo.el ends here
